spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/imooc-demo?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
  session:
    store-type: none
imooc:
  security:
    browser:
      sign-up-url: /demo-singUp.html
#      login-page: /demo-signIn.html
#      login-type: JSON
#    code:
#      image:
#        length:
#        width: 100
#        url: /user,/user/*
#      sms:
#        url: /user
#        length: 4
    social:
      qq:
        app-id: 101892374
        app-secret: 5040db8a60987cabed4ba0d30aa3c82b
        provider-id: qq
      filter-processes-url: /qqLogin
      weixin:
        app-id:
        app-secret:

server:
  port: 80
